import heroGym from "@/assets/pitch/hero-gym.jpg";
import heroRecovery from "@/assets/pitch/hero-recovery.jpg";
import heroTrack from "@/assets/pitch/hero-track.jpg";
import heroPersonalTraining from "@/assets/pitch/hero-personal-training.jpg";
import heroConstruction from "@/assets/pitch/hero-construction.jpg";
import heroSwimmingPool from "@/assets/pitch/hero-swimming-pool.jpg";
import heroFacility from "@/assets/pitch/hero-facility-v2.jpg";
import heroFilmStudio from "@/assets/pitch/hero-film-studio.jpg";
import heroPilates from "@/assets/pitch/hero-pilates.jpg";
import heroRockClimbing from "@/assets/pitch/hero-rockclimbing.jpg";
import heroYouthSports from "@/assets/pitch/hero-youth-sports.jpg";
import type { RevenueStreamData } from "./SlideRevenueStream";

export const revenueStreams: RevenueStreamData[] = [
  {
    icon: "🏋️",
    title: "Monthly Memberships",
    subtitle: "Tiered access plans for individuals and families",
    total: "$360K – $540K",
    type: "core",
    heroImage: heroGym,
    assumptions: [
      { label: "Year 1 Target Members", value: "275" },
      { label: "Basic Tier ($99/mo)", value: "~40% of members" },
      { label: "Performance Tier ($149/mo)", value: "~35% of members" },
      { label: "Elite Tier ($199/mo)", value: "~25% of members" },
      { label: "Avg Revenue/Member", value: "$140/mo" },
      { label: "Annual Churn Rate", value: "~20%" },
    ],
    formula: "275 members × $140 avg/mo × ~10 effective months (accounting for ramp-up) = $360K low-end. At full capacity with upsells and family add-ons: $540K.",
    description: "Three-tiered membership structure. Basic covers gym access and group classes. Performance adds recovery suite, coaching sessions, and sport-specific training. Elite is all-inclusive with unlimited neuromuscular therapy, personal training, and priority booking.",
    defensibility: "Premium pricing justified by integrated services no competitor offers — recovery, medical, 30+ disciplines. Members aren't just joining a gym; they're accessing a full athletic ecosystem. High switching costs once athletes build programming with coaches.",
  },
  {
    icon: "🏈",
    title: "Team Retainments",
    subtitle: "Dedicated facility access for organized sports teams",
    total: "$180K",
    type: "core",
    heroImage: heroTrack,
    assumptions: [
      { label: "Target Teams Retained", value: "6" },
      { label: "Avg Monthly Retainer", value: "$2,500" },
      { label: "Contract Length", value: "12 months" },
      { label: "Includes", value: "Priority scheduling" },
      { label: "Team Size Range", value: "15–50 athletes" },
      { label: "Off-Season Training Add-On", value: "$500/mo" },
    ],
    formula: "6 teams × $2,500/mo × 12 months = $180K. Off-season add-ons and tournament prep packages provide upside beyond base retainer.",
    description: "Local high school, AAU, club, and semi-pro teams retain Iron Form for dedicated training blocks, facility access, and coaching support. Includes reserved court/field time, team recovery sessions, and strength & conditioning programming.",
    defensibility: "Atlanta has 100+ competitive youth and club teams within 30 miles. No facility currently offers multi-sport team retainer packages with integrated recovery. Once a team builds their season around our facility, switching is disruptive and costly.",
  },
  {
    icon: "🏥",
    title: "Insurance Partnerships",
    subtitle: "Workers' comp referrals and insurer-funded programs",
    total: "$125K",
    type: "core",
    heroImage: heroRecovery,
    assumptions: [
      { label: "Workers' Comp Referrals/Week", value: "20" },
      { label: "Avg Session Rate", value: "$100" },
      { label: "Active Weeks/Year", value: "50" },
      { label: "Insurer Premium Partnerships", value: "2–3" },
      { label: "Per-Member Subsidy", value: "$25–$50/mo" },
      { label: "Subsidized Members", value: "~80" },
    ],
    formula: "Rehab referrals: 20/week × $100 × 50 weeks = $100K. Insurer subsidies: 80 members × $35 avg/mo × 12 = $33K. Blended conservative: $125K.",
    description: "Insurance companies pay for approved rehab sessions at our facility, leveraging our neuromuscular therapy team and recovery suite. Separately, health insurers subsidize member premiums to reduce their claims costs by promoting active lifestyles.",
    defensibility: "Our on-staff neuromuscular therapy director (18+ years experience) and integrated medical suite qualify us for referral programs that standard gyms cannot access. Rick Villanueva's credentials are the moat.",
  },
  {
    icon: "🏟️",
    title: "Facility Rentals",
    subtitle: "Event space, production rentals, and private bookings",
    total: "$156K",
    type: "core",
    heroImage: heroConstruction,
    assumptions: [
      { label: "Rentable Sq Ft", value: "~15,000" },
      { label: "Avg Rental Rate", value: "$1,000/event" },
      { label: "Rentals Per Week", value: "3" },
      { label: "Active Weeks/Year", value: "50" },
      { label: "Film/Production Premium", value: "2x rate" },
      { label: "Weekend Tournament Rate", value: "$2,500/day" },
    ],
    formula: "3 rentals/week × $1,000 avg × 50 weeks = $150K. Film/production premium events add ~$6K. Conservative total: $156K.",
    description: "60,000 sq ft facility with track, pool, climbing wall, spring floors, and open training space. Available for weekend tournaments, corporate offsites, film productions, private events, and community functions. Film productions pay premium rates for gantry rigs and spring floors.",
    defensibility: "Atlanta event space runs $3–5K/day. Our pricing is competitive while offering unique athletic infrastructure. Film industry demand in Georgia (#1 production state) creates a pipeline no traditional gym can serve.",
  },
  {
    icon: "🏢",
    title: "Corporate Wellness",
    subtitle: "Enterprise health & fitness programs for Atlanta companies",
    total: "$180K",
    type: "enhanced",
    heroImage: heroPersonalTraining,
    assumptions: [
      { label: "Target Corporate Clients", value: "3" },
      { label: "Avg Monthly Contract", value: "$5,000" },
      { label: "Contract Length", value: "12 months" },
      { label: "Employees per Client", value: "50–200" },
      { label: "Industry Benchmark/Employee", value: "$600+/yr" },
      { label: "Fortune 500s in Atlanta", value: "18" },
    ],
    formula: "3 clients × $5,000/mo × 12 months = $180K. Conservative Year 1 — corporate sales cycles are 3–6 months. Year 2 target: 5+ clients ($300K+).",
    description: "Tiered corporate packages including employee gym access, on-site wellness workshops, team-building fitness events, and executive recovery programs. Targets Atlanta's dense concentration of Fortune 500 headquarters and large employers.",
    defensibility: "Atlanta has 18 Fortune 500 HQs and thousands of mid-market employers. Industry spend is $600+/employee/year and rising. Our integrated recovery and medical differentiator wins contracts over standard gym partnerships. Corporate wellness reduces insurance costs — CFOs love the ROI story.",
  },
  {
    icon: "⛺",
    title: "Camps & Seminars",
    subtitle: "Youth sports camps, adult clinics, and coaching workshops",
    total: "$144K",
    type: "enhanced",
    heroImage: heroYouthSports,
    assumptions: [
      { label: "Camp Seasons/Year", value: "4 (seasonal)" },
      { label: "Avg Campers/Season", value: "30" },
      { label: "Camp Fee", value: "$400/week" },
      { label: "Adult Seminars/Month", value: "2" },
      { label: "Seminar Fee", value: "$75/person" },
      { label: "Avg Seminar Attendance", value: "40" },
    ],
    formula: "Camps: 4 seasons × 30 kids × $400 = $48K. Seminars: 2/month × 40 people × $75 × 12 months = $72K. Certification workshops: $24K. Total: $144K.",
    description: "Multi-sport youth camps during school breaks (spring, summer, fall, winter). Adult seminars on training methodology, nutrition, recovery science. Coach certification workshops and continuing education events.",
    defensibility: "Youth sports camps are high-margin with pre-paid registration. Our 30+ discipline offering means camps cover martial arts, track, swimming, climbing — parents love the variety. Seminar series builds community authority and pipeline to memberships.",
  },
  {
    icon: "📱",
    title: "Digital Memberships",
    subtitle: "Online training programs, classes, and content access",
    total: "$84K",
    type: "enhanced",
    heroImage: heroPilates,
    assumptions: [
      { label: "Year 1 Digital Subscribers", value: "600–800" },
      { label: "Monthly Subscription", value: "$9.99/mo" },
      { label: "Content Library", value: "100+ videos" },
      { label: "Live Stream Classes/Week", value: "5" },
      { label: "Conversion from Free Tier", value: "~15%" },
      { label: "Growth Rate (M/M)", value: "8–10%" },
    ],
    formula: "700 avg subscribers × $10/mo × 12 months = $84K. Conservative Year 1 — digital takes time to build audience. Year 2 target: 1,500+ subs ($180K).",
    description: "On-demand workout library, live-streamed classes, training programming, and recovery protocols. Accessible globally — extends Iron Form's brand beyond Atlanta. Free tier drives awareness; paid tier unlocks full library and live interaction.",
    defensibility: "Year 1 is intentionally conservative. Digital is a long-game play — low marginal cost once content is produced. Our unique disciplines (stunt training, circus arts, neuromuscular education) differentiate us from generic fitness apps.",
  },
  {
    icon: "🏷️",
    title: "Naming Rights & Sponsorships",
    subtitle: "Facility branding, signage, and sponsor integrations",
    total: "$200K",
    type: "enhanced",
    heroImage: heroFacility,
    assumptions: [
      { label: "Naming Rights (Main Facility)", value: "$80K/yr" },
      { label: "Zone Sponsorships (5 zones)", value: "$12K each" },
      { label: "Equipment Sponsors", value: "$30K total" },
      { label: "Apparel/Gear Partnerships", value: "$15K" },
      { label: "Digital Display Ads", value: "$10K" },
      { label: "Event Title Sponsors", value: "$5K" },
    ],
    formula: "Naming: $80K + Zone sponsors: 5 × $12K = $60K + Equipment: $30K + Apparel: $15K + Digital: $10K + Events: $5K = $200K. Year 1 conservative — scales to $350K+ with proven foot traffic in Year 2.",
    description: "Naming rights for the main facility and individual training zones (e.g., 'The Nike Recovery Suite'). Equipment sponsorships from brands like Rogue, Concept2, Eleiko. Apparel partnerships with athletic brands. Digital signage network throughout the facility.",
    defensibility: "60,000 sq ft with 275+ members, corporate clients, and community events gives sponsors guaranteed impressions. Atlanta market size (6M+ metro) and our target demographic (affluent, active, 18–55) is sponsor gold. Comparable facilities in other markets command $200K–$500K for naming alone.",
  },
  {
    icon: "🏆",
    title: "Event Hosting",
    subtitle: "Competitions, showcases, and community fitness events",
    total: "$150K",
    type: "enhanced",
    heroImage: heroRockClimbing,
    assumptions: [
      { label: "Major Events/Year", value: "6" },
      { label: "Avg Revenue/Major Event", value: "$12K" },
      { label: "Monthly Community Events", value: "2" },
      { label: "Avg Revenue/Community Event", value: "$3K" },
      { label: "Spectator Capacity", value: "500+" },
      { label: "Vendor/Booth Fees", value: "$500–$1K" },
    ],
    formula: "Major events: 6 × $12K = $72K. Community events: 2/mo × $3K × 12 = $72K. Vendor fees and concessions: ~$6K. Total: $150K.",
    description: "Host Hyrox qualifiers, CrossFit throwdowns, strongman competitions, martial arts tournaments, youth track meets, and climbing comps. Revenue from entry fees, spectator tickets, vendor booths, and food/beverage. Community events include open gym nights, charity workouts, and fitness challenges.",
    defensibility: "Atlanta's youth sports market is massive — parents will travel for quality competitions. Our multi-sport facility can host events no single-discipline gym can. Each event markets our facility to hundreds of potential members. Event hosting has a 60%+ profit margin.",
  },
  {
    icon: "❄️",
    title: "Recovery Drop-Ins",
    subtitle: "Pay-per-session cryo, cold plunge, compression, and therapy",
    total: "$120K",
    type: "enhanced",
    heroImage: heroRecovery,
    assumptions: [
      { label: "Daily Drop-In Visits", value: "10" },
      { label: "Avg Session Price", value: "$40" },
      { label: "Operating Days/Year", value: "300" },
      { label: "Services Offered", value: "6+" },
      { label: "Package Discounts (10-pack)", value: "$350" },
      { label: "Peak Weekend Premium", value: "+25%" },
    ],
    formula: "10 visits/day × $40 avg × 300 days = $120K. Package pre-sales and weekend premiums provide additional upside.",
    description: "Non-members can access recovery services à la carte: cryotherapy ($45), cold plunge ($25), Normatec compression ($35), infrared sauna ($30), PEMF therapy ($50), and neuromuscular sessions ($85+). Package bundles incentivize repeat visits and eventual membership conversion.",
    defensibility: "Recovery wellness is the fastest-growing fitness segment. Standalone cryo studios charge $40–75/session with less to offer. Our full suite under one roof with a licensed neuromuscular therapist is unmatched. Drop-ins are also the #1 membership conversion funnel — 30%+ convert within 60 days.",
  },
  {
    icon: "🎬",
    title: "Content & Media",
    subtitle: "Branded content, licensing, and media production revenue",
    total: "$36K",
    type: "enhanced",
    heroImage: heroFilmStudio,
    assumptions: [
      { label: "YouTube/Social Ad Revenue", value: "$6K/yr" },
      { label: "Branded Content Deals", value: "3–4/yr" },
      { label: "Avg Branded Deal", value: "$5K" },
      { label: "Licensing (Training Programs)", value: "$8K" },
      { label: "Podcast/Media Sponsorships", value: "$4K" },
      { label: "Affiliate Commissions", value: "$3K" },
    ],
    formula: "YouTube/social: $6K + Branded content: 3.5 × $5K = $17.5K + Licensing: $8K + Podcast: $4K + Affiliate: $3K ≈ $36K. Conservative Year 1.",
    description: "Content monetization through branded training videos, sponsored athlete features, equipment reviews, and educational series. Licensing proprietary training methodologies to other facilities. Podcast and media partnerships leveraging our unique positioning at the intersection of athletics and entertainment.",
    defensibility: "Year 1 is conservatively low — content takes time to build audience. But our unique content (stunt training BTS, circus arts, multi-sport athlete journeys) is genuinely differentiated in a sea of generic fitness content. Year 2+ scales significantly as audience grows. Near-zero marginal cost.",
  },
  {
    icon: "🏃",
    title: "Personal Training",
    subtitle: "One-on-one and small group coaching sessions",
    total: "$300K",
    type: "core",
    heroImage: heroPersonalTraining,
    assumptions: [
      { label: "Trainers on Staff", value: "10" },
      { label: "Sessions/Trainer/Week", value: "15" },
      { label: "Avg Session Price", value: "$80" },
      { label: "Facility Split", value: "50%" },
      { label: "Active Weeks/Year", value: "50" },
      { label: "Small Group Premium", value: "+30%" },
    ],
    formula: "10 trainers × 15 sessions/week × $80 × 50 weeks = $600K gross. After 50% trainer split: $300K net to facility. Small group sessions add upside.",
    description: "One-on-one personal training across all disciplines — strength, sport-specific, rehab-focused, and performance coaching. Small group sessions (2–4 people) at premium rates. Trainers are independent contractors with revenue-share model, keeping facility costs low.",
    defensibility: "Personal training is the #1 revenue driver at premium facilities (15–25% of total). Our 30+ discipline roster means we offer specialized coaching no single-sport gym can. Trainer retention is high when they have access to world-class equipment and a built-in client pipeline.",
  },
  {
    icon: "💉",
    title: "Peptide & IV Wellness Clinic",
    subtitle: "Performance wellness, IV therapy, and peptide protocols",
    total: "$300K",
    type: "enhanced",
    heroImage: heroRecovery,
    assumptions: [
      { label: "IV Therapy Sessions/Day", value: "6" },
      { label: "Avg IV Session Price", value: "$200" },
      { label: "Peptide Protocol Clients", value: "40/month" },
      { label: "Avg Protocol Revenue", value: "$350/mo" },
      { label: "Operating Days/Year", value: "300" },
      { label: "Clinic Director", value: "Josh Garret" },
    ],
    formula: "IV therapy: 6/day × $200 × 300 days = $360K gross. Peptide protocols: 40 clients × $350/mo × 12 = $168K. After COGS (~40%): ~$300K net. Conservative — demand is explosive.",
    description: "Full-service wellness clinic run by Josh Garret offering IV hydration drips ($150–$300), peptide therapy protocols (BPC-157, Thymosin, etc.), hormone optimization, and performance wellness consultations. Located within the facility for seamless athlete access.",
    defensibility: "Peptide and IV wellness is a $5B+ market growing 12%+ annually. Having the clinic inside an elite training facility creates a natural referral pipeline — athletes train, recover, and optimize in one location. Josh's background in performance wellness protocols is the clinical anchor.",
  },
  {
    icon: "🥤",
    title: "Nutrition Hub & Café",
    subtitle: "Smoothie bar, healthy café, and meal prep services",
    total: "$150K",
    type: "enhanced",
    heroImage: heroGym,
    assumptions: [
      { label: "Avg Daily Transactions", value: "60" },
      { label: "Avg Ticket (Smoothie/Meal)", value: "$12" },
      { label: "Operating Days/Year", value: "300" },
      { label: "Meal Prep Subscribers", value: "50" },
      { label: "Weekly Meal Prep Price", value: "$75" },
      { label: "Gross Margin", value: "55–65%" },
    ],
    formula: "Counter sales: 60/day × $12 × 300 days = $216K. Meal prep: 50 subs × $75/week × 50 weeks = $187K. Total gross: $403K. After COGS (~60%): ~$150K net.",
    description: "Post-workout smoothie bar, healthy grab-and-go café, and weekly meal prep subscription service. Menu designed by sports nutritionists — protein bowls, recovery smoothies, performance meals. Meal prep delivers to members' homes or available for facility pickup.",
    defensibility: "Athletes need to eat — our café captures spend that otherwise leaves the facility. Meal prep subscriptions create recurring revenue with high retention. The nutrition hub extends visit duration and builds community. 55–65% gross margins on prepared food are industry standard.",
  },
  {
    icon: "🛍️",
    title: "Pro Shop & Retail",
    subtitle: "Equipment, supplements, branded merchandise, and gear",
    total: "$50K",
    type: "enhanced",
    heroImage: heroGym,
    assumptions: [
      { label: "Avg Monthly Revenue", value: "$4,200" },
      { label: "Branded Merch (Shirts, Bags)", value: "$15K/yr" },
      { label: "Supplements & Nutrition", value: "$18K/yr" },
      { label: "Equipment & Gear", value: "$12K/yr" },
      { label: "Gross Margin", value: "40–50%" },
      { label: "Online Store Add-On", value: "$5K/yr" },
    ],
    formula: "Merch: $15K + Supplements: $18K + Equipment: $12K + Online: $5K = $50K. Low overhead — mostly inventory management and point-of-sale.",
    description: "On-site pro shop selling Iron Form branded apparel, training gloves, wraps, supplements, recovery tools, and specialty equipment. Online store extends reach beyond facility. Supplement partnerships with brands like Thorne and Momentous for premium margins.",
    defensibility: "Low-risk, low-overhead revenue stream. Branded merch builds brand equity while generating income. Supplement sales are high-margin and naturally driven by trainer recommendations. Scales with membership growth — minimal additional investment needed.",
  },
];
